<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBo7wal4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBo7wal4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBo7wal4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBo7wal4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBo7wal4\appProdProjectContainer([
    'container.build_hash' => 'Bo7wal4',
    'container.build_id' => '80d26f57',
    'container.build_time' => 1552579251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBo7wal4');
